export enum ROUTES {
  BASE = "/",
  PAGE_NOT_FOUND = "*",
  NEW_ID_VALUE = "new",
  LOGIN = "/login",
  SIGN_UP = "/signup",
  FORGOT_PASSWORD = "/forgotpassword",
  RESET_PASSWORD = "/resetpassword/",
  CREATE_NEW_PASSWORD = "/create-new-password/",
  BASE_HOME = "/home/*",
  HOME = "/home",
  DASHBOARD = "/dashboard",
  CHANGE_PASSWORD = "/profile/change-password/",
  SUPPORT = "/support",
  LIST = "/list",
  VIEW_DETAILS = "/view/:id",
  ADD_DETAILS = "/add",
  VIEW = "/view",
  EDIT_DETAILS = "/edit/:id",
  EDIT = "/edit",
  DELETE_DETAILS = "/delete/:id",
}
